openapi: 3.0.4
info:
  title: Currency Converter
  description: Currency Converter is a simple tool for converting currency rates. It returns the converted currency rate based on the amount and currency provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/currencyconverter:
    get:
      summary: Convert Currency Rates
      description: Currency Converter is a simple tool for converting currency rates. It returns the converted currency rate based on the amount and currency provided.
      operationId: currencyconverter
      parameters:
      - name: value
        in: query
        schema:
          type: number
        required: true
        description: The amount to convert
        example: '1'
      - name: from
        in: query
        schema:
          type: string
        required: true
        description: The currency code to convert from
        example: USD
      - name: to
        in: query
        schema:
          type: string
        required: true
        description: The currency code to convert to
        example: EUR
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  from: USD
                  to: EUR
                  value: 1
                  convertedValue: 0.95466
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
